<?php
/**
 * This class has been auto-generated by PHP-DI.
 */
class CompiledContainer extends DI\CompiledContainer{
    const METHOD_MAPPING = array (
  'SuperBlog\\Persistence\\HouseCache' => 'get1',
  'SuperBlog\\Model\\ArticleRepository' => 'get2',
  'SuperBlog\\Model\\HouseRepository' => 'get3',
  'subEntry1' => 'get4',
  'Twig\\Environment' => 'get5',
);

    protected function get1()
    {
        return $this->resolveFactory(static function(){
        return new \SuperBlog\Persistence\HouseCache();
    }, 'SuperBlog\\Persistence\\HouseCache');
    }

    protected function get2()
    {
        $object = new SuperBlog\Persistence\InMemoryArticleRepository();
        return $object;
    }

    protected function get4()
    {
        return $this->delegateContainer->get('SuperBlog\\Persistence\\HouseCache');
    }

    protected function get3()
    {
        $object = new SuperBlog\Persistence\InMemoryHouseRepository($this->get4());
        return $object;
    }

    protected function get5()
    {
        return $this->resolveFactory(static function () {
        $loader = new \Twig\Loader\FilesystemLoader('C:\\Users\\b1k\\Desktop\\php\\demo\\app' . '/../src/SuperBlog/Views');
        return new \Twig\Environment($loader);
    }, 'Twig\\Environment');
    }

}
